### ISSUE TITLE
InvalidArgumentError: input_1_1:0 is both fed and fetched.

### ISSUE THREAD

**Issue by peterhsu2018** [raghakot/keras-vis#145]
run example/resnet/attention.ipynb
and change to the model  with my custom resnet50 like this:
   model_path = os.path.join('../../../saved_models', 'res50transfer_learning.h5')
   model = load_model(model_path)

   layer_idx = utils.find_layer_idx(model, 'dense_1')

my environment
Keras 2.2.2
Tensorflow 1.10
Keras-vis 0.4.1

**Comment by keisen** [comment]
Hi @peterhsu2018 .
Sorry, keras-vis was not released that this problem was fixed.
So please directly re-install keras-vis via github.

```
pip install git+https://github.com/raghakot/keras-vis.git -U
```

This issue should have fixed by PR #120 , so I'll close this.
But if I made mistaken, please feel free to reopen.

**Comment by peterhsu2018** [comment]
> Hi @peterhsu2018 .
> Sorry, keras-vis was not released that this problem was fixed.
> So please directly re-install keras-vis via github.
> 
> ```
> pip install git+https://github.com/raghakot/keras-vis.git -U
> ```
> This issue should have fixed by PR #120 , so I'll close this.
> But if I made mistaken, please feel free to reopen.
> 
> Thanks!

Hi @keisen
This is helpful for me
Thanks a lot!

**Comment by lrsoenksen** [comment]
> Hi @peterhsu2018 .
> Sorry, keras-vis was not released that this problem was fixed.
> So please directly re-install keras-vis via github.
> 
> ```
> pip install git+https://github.com/raghakot/keras-vis.git -U
> ```
> This issue should have fixed by PR #120 , so I'll close this.
> But if I made mistaken, please feel free to reopen.
> 
> Thanks!

This response by @keisen worked for me too, but only after doing a fresh re-install

pip uninstall keras-vis
pip install git+https://github.com/raghakot/keras-vis.git -U

-then refresh env in jupyter notebook and done! It should be working =)

**Comment by fsteiner** [comment]
Hello  @peterhsu2018

I just tried the fix and it did not work for me. 
I am running keras 2.2.4 with tf  1.9.0.
I am not very knowledgeable with the intricacies of the system, would you have any suggestions on what I could do next?

Many thanks!

**Comment by fsteiner** [comment]
Hello @keisen 

I just tried the fix and it did not work for me.
I am running keras 2.2.4 with tf 1.9.0.
I am not very knowledgeable with the intricacies of the system, would you have any suggestions on what I could do next?

Many thanks!

**Comment by michiexile** [comment]
Installed keras-vis from the github, and reinstalled both keras and tensorflow. I am still getting this error.


```
from tensorflow.keras import layers, models, datasets, utils

inp = layers.Input((28,28))
x = layers.Flatten()(inp)
x = layers.BatchNormalization()(x)
x = layers.Dense(1024, activation="relu")(x)
x = layers.Dense(512, activation="relu")(x)
x = layers.Dense(128, activation="relu")(x)
oup = layers.Dense(10, activation="softmax")(x)

model = models.Model(inputs=inp, outputs=oup)
model.compile("rmsprop", loss="categorical_crossentropy", metrics=["accuracy"])

(X_train,y_train),(X_test,y_test) = datasets.fashion_mnist.load_data()
y_train = utils.to_categorical(y_train)
y_test = utils.to_categorical(y_test)

model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=1)

from vis import visualization, utils
from keras import activations

layer_idx = -1

model.layers[layer_idx].activation = activations.linear
model.save("tmp.model")
model = models.load_model("tmp.model")

grads = visualization.visualize_saliency(model, 2, 
   filter_indices=0,
   seed_input=X_test[0])
```

**Comment by indramal** [comment]
> Installed keras-vis from the github, and reinstalled both keras and tensorflow. I am still getting this error.
> 
> ```
> from tensorflow.keras import layers, models, datasets, utils
> 
> inp = layers.Input((28,28))
> x = layers.Flatten()(inp)
> x = layers.BatchNormalization()(x)
> x = layers.Dense(1024, activation="relu")(x)
> x = layers.Dense(512, activation="relu")(x)
> x = layers.Dense(128, activation="relu")(x)
> oup = layers.Dense(10, activation="softmax")(x)
> 
> model = models.Model(inputs=inp, outputs=oup)
> model.compile("rmsprop", loss="categorical_crossentropy", metrics=["accuracy"])
> 
> (X_train,y_train),(X_test,y_test) = datasets.fashion_mnist.load_data()
> y_train = utils.to_categorical(y_train)
> y_test = utils.to_categorical(y_test)
> 
> model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=1)
> 
> from vis import visualization, utils
> from keras import activations
> 
> layer_idx = -1
> 
> model.layers[layer_idx].activation = activations.linear
> model.save("tmp.model")
> model = models.load_model("tmp.model")
> 
> grads = visualization.visualize_saliency(model, 2, 
>    filter_indices=0,
>    seed_input=X_test[0])
> ```

First, remove all vis packages by the following code,

```
pip uninstall vis
pip uninstall keras-vis
pip uninstall keras-vis-temp
```

Then install keras vis,
`pip install git+https://github.com/raghakot/keras-vis.git -U`
